"""empty message

Revision ID: 216a2f310ee7
Revises: 0763d677d453
Create Date: 2026-07-16 01:32:20.374679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216a2f310ee7'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ejercicio',
    sa.Column('EjercicioID', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('EjercicioID')
    )
    op.create_table('Usuario',
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.Column('Correo', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('urlFoto', sa.String(length=100), nullable=False),
    sa.Column('Altura', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('Objetivo', sa.String(length=100), nullable=False),
    sa.Column('PesoDeseado', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('UsuarioID'),
    sa.UniqueConstraint('Correo')
    )
    op.create_table('CodigoRecuperacion',
    sa.Column('RecuperacionID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('Codigo', sa.String(length=10), nullable=False),
    sa.Column('FechaSolicitud', sa.DateTime(), nullable=False),
    sa.Column('FechaExpiracion', sa.DateTime(), nullable=False),
    sa.Column('Estatus', sa.Enum('ACTIVO', 'EXPIRADO', 'USADO', name='estatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioID'], ['Usuario.UsuarioID'], ),
    sa.PrimaryKeyConstraint('RecuperacionID')
    )
    op.create_table('Entrenamiento',
    sa.Column('EntrenamientoID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.Date(), nullable=False),
    sa.Column('Duracion', sa.Integer(), nullable=False),
    sa.Column('Nota', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioID'], ['Usuario.UsuarioID'], ),
    sa.PrimaryKeyConstraint('EntrenamientoID')
    )
    op.create_table('Nutricion',
    sa.Column('NutricionID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('TipoComida', sa.Enum('DESAYUNO', 'ALMUERZO', 'CENA', 'MERIENDA', name='tipocomidaenum'), nullable=False),
    sa.Column('Fecha', sa.Date(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Proteina', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('Caloria', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('Grasa', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('Carbohidrato', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioID'], ['Usuario.UsuarioID'], ),
    sa.PrimaryKeyConstraint('NutricionID')
    )
    op.create_table('Peso',
    sa.Column('PesoID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.Date(), nullable=False),
    sa.Column('PesoKg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioID'], ['Usuario.UsuarioID'], ),
    sa.PrimaryKeyConstraint('PesoID')
    )
    op.create_table('PlanIA',
    sa.Column('PlanID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.Date(), nullable=False),
    sa.Column('TipoPlan', sa.Enum('ENTRENAMIENTO', 'NUTRICION', name='tipoplanenum'), nullable=False),
    sa.Column('Prompt', sa.Text(), nullable=False),
    sa.Column('Resultado', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioID'], ['Usuario.UsuarioID'], ),
    sa.PrimaryKeyConstraint('PlanID')
    )
    op.create_table('DetalleEntrenamiento',
    sa.Column('DetEntrenamientoID', sa.Integer(), nullable=False),
    sa.Column('EntrenamientoID', sa.Integer(), nullable=False),
    sa.Column('EjercicioID', sa.Integer(), nullable=False),
    sa.Column('Serie', sa.Integer(), nullable=False),
    sa.Column('Repeticion', sa.Integer(), nullable=False),
    sa.Column('PesoEjercicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EjercicioID'], ['Ejercicio.EjercicioID'], ),
    sa.ForeignKeyConstraint(['EntrenamientoID'], ['Entrenamiento.EntrenamientoID'], ),
    sa.PrimaryKeyConstraint('DetEntrenamientoID')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('DetalleEntrenamiento')
    op.drop_table('PlanIA')
    op.drop_table('Peso')
    op.drop_table('Nutricion')
    op.drop_table('Entrenamiento')
    op.drop_table('CodigoRecuperacion')
    op.drop_table('Usuario')
    op.drop_table('Ejercicio')
    # ### end Alembic commands ###
