"""empty message

Revision ID: 6d359d234508
Revises: 
Create Date: 2026-02-04 18:21:08.135689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d359d234508'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('imagen', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lunes_entrada', sa.Time(), nullable=False),
    sa.Column('lunes_salida', sa.Time(), nullable=False),
    sa.Column('martes_entrada', sa.Time(), nullable=False),
    sa.Column('martes_salida', sa.Time(), nullable=False),
    sa.Column('miercoles_entrada', sa.Time(), nullable=False),
    sa.Column('miercoles_salida', sa.Time(), nullable=False),
    sa.Column('jueves_entrada', sa.Time(), nullable=False),
    sa.Column('jueves_salida', sa.Time(), nullable=False),
    sa.Column('viernes_entrada', sa.Time(), nullable=False),
    sa.Column('viernes_salida', sa.Time(), nullable=False),
    sa.Column('sabado_entrada', sa.Time(), nullable=True),
    sa.Column('sabado_salida', sa.Time(), nullable=True),
    sa.Column('domingo_entrada', sa.Time(), nullable=True),
    sa.Column('domingo_salida', sa.Time(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('puede_crear_reunion', sa.Boolean(), nullable=False),
    sa.Column('puede_compartir_reunion', sa.Boolean(), nullable=False),
    sa.Column('puede_añadir_tareas', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('dni', sa.String(length=9), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('foto_perfil', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'ausente', 'ocupado', 'no_molestar', name='estadouser'), nullable=False),
    sa.Column('link_calendly', sa.String(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fichaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hora_entrada', sa.DateTime(), nullable=True),
    sa.Column('hora_salida', sa.DateTime(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reunion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('organizador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizador_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reunion_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reunion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reunion_id'], ['reunion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reunion_user')
    op.drop_table('tarea')
    op.drop_table('reunion')
    op.drop_table('fichaje')
    op.drop_table('user')
    op.drop_table('rol')
    op.drop_table('horario')
    op.drop_table('empresa')
    # ### end Alembic commands ###
