"""empty message

Revision ID: 817fd86459da
Revises: f54fe3d57be0
Create Date: 2026-06-15 18:46:49.450552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817fd86459da'
down_revision = 'f54fe3d57be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
