"""empty message

Revision ID: 946506b65300
Revises: f18b939bd3cd
Create Date: 2026-03-31 22:46:47.387240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946506b65300'
down_revision = 'f18b939bd3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('equipment', sa.String(length=120), nullable=False),
    sa.Column('execution', sa.Text(), nullable=False),
    sa.Column('preparation', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine_exercises',
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('routine_id', 'exercise_id')
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_column('exercises')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercises', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('routine_exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
