"""Add attended fields to assigned_classes

Revision ID: f18b939bd3cd
Revises: 4bf68c2e5137
Create Date: 2026-03-31 02:29:43.342645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18b939bd3cd'
down_revision = '4bf68c2e5137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attended', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('attended_date', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_classes', schema=None) as batch_op:
        batch_op.drop_column('attended_date')
        batch_op.drop_column('attended')

    # ### end Alembic commands ###
